name: Ejecucion Batch Diaria

on:
  schedule:
    # Ejecuta de lunes a viernes a las 11:00 UTC (08:00 ARG)
    - cron: '0 11 * * 1-5'
  workflow_dispatch: # Permite ejecución manual desde GitHub

jobs:
  run-ensamblador:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar Código
        uses: actions/checkout@v4
        
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_backend.txt
          
      - name: Inyectar Credenciales (Base64)
        env:
          JSON_BASE64: ${{ secrets.JSON_FILE_CONTENT_BASE64 }}
          API_KEY_BASE64: ${{ secrets.API_KEY_FILE_CONTENT_BASE64 }}
        run: |
          echo "Creando carpeta creds y decodificando secretos Base64..."
          mkdir -p creds
          echo "$API_KEY_BASE64" | base64 --decode > creds/api_key.txt
          echo "$JSON_BASE64" | base64 --decode > creds/python-sheets-492415-9f916d7c2cd1.json
          
      - name: Ejecutar Orquestador
        env:
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_STRING_SESSION: ${{ secrets.TELEGRAM_STRING_SESSION }}
        run: |
          python ensamblador.py
